### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by mehmetg**
Accessibility Id's fixed.

### CODE REVIEW

**Comment by mehmetg** [comment]
@KevinMarkVI @ndmanvar Here's the source for the test app.

**Comment by ndmanvar** [comment]
mehmet, this is awesome. :+1:

**Comment by mehmetg** [comment]
@ndmanvar Thanks. I am hoping to add unit tests to test it from within XCode. It'll be an adventure so I will take it slow,

**Comment by KevinMarkVI** [comment]
Thumbs up from me.

**Comment by mehmetg** [comment]
Thank you for reviewing. 
I'll hold pending the resolution of https://saucedev.atlassian.net/browse/RDC-199

**Pull request merged**
